---
- name: include variables I
  include_vars: '{{ item }}'
  with_items: '{{ ( "vars/*.yml" | fileglob + ["data/vars.yml"] ) }}'

- name: render variable templates I
  template:
    src: '{{ item }}'
    dest: '{{ item | splitext | first }}'
  with_items: '{{ ( "data/**/vars.yml.j2" | fileglob ) }}'

- name: include variables II
  include_vars:
    file: '{{ item }}'
  loop: '{{ "data/**/vars.yml" | fileglob }}'

