---

- include_tasks:
    file: tasks/symlinks.yml

- fail: {msg:""}

- name: install packages
  package:
    name: "{{ programs.packages }}"
    state: present
  become: yes

- name: find post-package hooks
  stat:
    path: "tasks/programs/post-{{ item }}.yml"
  with_items: "{{ programs.packages }}"
  register: _program_stat

- name: run post-package hooks
  include_tasks: "tasks/programs/post-{{ item.item }}.yml"
  when: item.stat.exists
  with_items: "{{ _program_stat.results }}"

- name: install custom programs
  include_tasks:
    file: "tasks/programs/{{ program }}.yml"
  with_items: "{{ programs.custom }}"
  when: programs.custom
  loop_control:
    loop_var: program

- file:
    path: '{{ services_home }}'
    state: directory
    mode: '755'
  become: yes

- name: clone services
  git:
    repo: '{{ services_repo }}'
    dest: '{{ services_home }}'
    force: no
    update: no
  become: yes

