---
- name: find templates
  find:
    paths: .
    patterns: "*.j2"
    recurse: true
    excludes:
    - vars.yml.j2
  register: template_files

- name: render templates
  template:
    src: '{{ item.path }}'
    dest: '{{ item.path | splitext | first }}'
  loop: '{{ template_files.files }}'
  loop_control:
    label: '{{ item.path }}'
