---
  - import_tasks: tasks/load_variables.yml
  - name: customize xfce
    xfconf:
      channel: '{{ item.channel }}'
      force_array: '{{ item.force_array | default(false) }}'
      property: '{{ item.property }}'
      value: '{{ item.value }}'
      value_type: '{{ item.type }}'
    loop: '{{ xfconf_settings }}'

