#!/bin/sh


# @getoptions
argparser_definition() {
  type generate_subcommand_parser_definitions >/dev/null || . $COMMANDS_DIR/_parse_args_helpers

	setup   REST help:usage abbr:true -- \
        "$(dotfiles_banner)" '' \
		"Usage: $PROGRAM [options...] <command> [...]"
	msg -- 'Options:'
	disp    :usage  -h --help

	msg -- '' 'Commands:'
	gen="$(generate_subcommand_parser_definitions "$COMMAND_PD")"
	eval "$gen"
}
[ "$(basename "$0")" = "gengetoptions" ] && return 0 || true
# @end
