#!/bin/sh

set -eu


COMMAND_DESCRIPTION="Generate the argument parsers for all dotfiles commands."
# @getoptions
argparser_definition() {
  type generate_subcommand_parser_definitions >/dev/null || . $COMMANDS_DIR/_parse_args_helpers

	setup   REST help:usage abbr:true -- \
        "$(dotfiles_banner)" '' '' \
		"Usage: $PROGRAM [options...]" '' \
        "$COMMAND_DESCRIPTION" ''
	msg -- 'Options:'
	param   SCRIPT  -s --script init:="$DOTFILES_MAIN_SCRIPT" -- "Name of the main script."
	disp    :usage  -h --help
}
[ "$(basename "$0")" = "gengetoptions" ] && return 0 || true
# @end

. "$COMMANDS_DIR/_parse_args"

find "$COMMANDS_DIR" -type f | while read -r file; do
  grep --quiet --max-count 1 "^argparser_definition" "$file" || continue
  echo "$file"
  program=$(
    echo "$file" | sed -e "s/^.\{$(echo "$COMMANDS_DIR" | wc -c)\}/$SCRIPT /; s|/| |; s|/*_$||; s/ $//"
  )
  env \
    DOTFILES_MAIN_SCRIPT="$DOTFILES_MAIN_SCRIPT" \
    COMMANDS_DIR="$COMMANDS_DIR" \
    COMMAND_PD="$(dirname "$file")" \
    COMMAND="$file" \
    PROGRAM="$program" \
    gengetoptions parser -f "$file" argparser_definition parse_args >"$file.parse_args"
done
