#!/bin/sh

set -eu


COMMAND_DESCRIPTION="Manage dotfiles' symlinks."
# @getoptions
argparser_definition() {
  type generate_subcommand_parser_definitions >/dev/null || . $COMMANDS_DIR/_parse_args_helpers

	setup   REST help:usage abbr:true -- \
        "$(dotfiles_banner)" '' '' \
		"Usage: $PROGRAM [options...]" '' \
        "$COMMAND_DESCRIPTION" ''
	msg -- 'Options:'
	flag    NO_BACKUPS --no-backups -- "Don't move existing configuration files to a backup (suffix them with a timestamp)."
	flag    DRY_RUN -n --dry-run -- "Show what would be done without actually doing any of it."
	disp    :usage  -h --help
}
[ "$(basename "$0")" = "gengetoptions" ] && return 0 || true
# @end

. "$COMMANDS_DIR/_parse_args"

do_unless_dry_run() {
	if [ "$DRY_RUN" = "1" ]; then
		echo "$@"
	else
		"$@"
	fi
}

create_link () {
  target="$1"
  name="$2"
  if [ -e "$target" ]; then
    if [ "$NO_BACKUPS" = "0" -a -f "$name" -a ! -L "$name" ]; then
      backup="$name-`date +%Y%m%dT%H%M%S`"
      do_unless_dry_run mv "$name" "$backup"
    fi
    do_unless_dry_run mkdir -p "`dirname \"$name\"`"
    do_unless_dry_run ln -fsT "$target" "$name"
  fi
}

create_link "$HOME/.config/dotfiles/data/git" "$HOME/.config/git"
create_link "$HOME/.config/dotfiles/data/tmux" "$HOME/.config/tmux"
create_link "$HOME/.config/dotfiles/data/vim" "$HOME/.config/vim"
create_link "$HOME/.config/dotfiles/data/nvim" "$HOME/.config/nvim"
create_link "$HOME/.config/dotfiles/data/nvchad" "$HOME/.config/nvchad"
create_link "$HOME/.config/dotfiles/data/starship/starship.toml" "$HOME/.config/starship.toml"
create_link "$HOME/.config/dotfiles/data/bash/bashrc" "$HOME/.bashrc"
create_link "$HOME/.config/dotfiles/data/shell/profile" "$HOME/.profile"
create_link "$HOME/.config/dotfiles/data/scripts/sshfs_auto.sh" "$HOME/.local/bin/sshfs-auto"
create_link "$HOME/.config/dotfiles/data/xinput/scripts/configure_pointer.sh" "$HOME/.local/bin/xinput-configure-pointer"
create_link "$HOME/.config/dotfiles/data/xinput/scripts/configure_pointer.desktop" "$HOME/.local/share/applications/xinput-configure-pointer.desktop"
create_link "$HOME/.config/dotfiles/data/xinput/scripts/toggle.sh" "$HOME/.local/bin/xinput-toggle"
