#!/bin/sh

set -eu

VENV_DIR="$DOTFILES_HOME/venv"

type python3 >/dev/null 2>&1 \
    && PYTHON3="python3" \
    || PYTHON3="python"

if [ -d "$VENV_DIR" -a -f "$VENV_DIR/bin/activate" ]; then
    . "$VENV_DIR/bin/activate"
fi
