#!/bin/sh

set -eu


COMMAND_DESCRIPTION="Renders templated files (marked with '.j2' extension)"

. "$COMMANDS_DIR/_python3_helper"

set -x
${PYTHON3} "$DOTFILES_HOME/data/scripts/render_templates.py" "$DOTFILES_HOME" "$@"
{ set +x; } 2>/dev/null
