environment_variables:
  CARGO_HOME: "${XDG_DATA_HOME:-$HOME/.local/share}/cargo" # otherwise ~/.cargo
  DOTFILES_HOME: "$HOME/.config/dotfiles"
  EDITOR: nvim
  HISTFILE: "${XDG_CACHE_HOME:-$HOME/.cache}/bash_history" # otherwise ~/.bash_history
  ICEAUTHORITY: "${XDG_CACHE_HOME:-$HOME/.cache}/ICEauthority" # otherwise ~/.ICEauthority
  INPUTRC: "${XDG_CONFIG_HOME:-$HOME/.config}/inputrc" # otherwise ~/.inputrc
  LC_TIME: en_CA.utf8
 #LC_NUMERIC: en_CA.utf8
  LESSHISTFILE: "${XDG_CACHE_HOME:-$HOME/.cache}/less_history" # otherwise ~/.lesshst
  NPM_CONFIG_USERCONFIG: "${XDG_CONFIG_HOME:-$HOME/.config}/npm/config" # otherwise ~/.npmconfig # https://github.com/npm/npm/issues/6675#issuecomment-251049832
  NPM_CONFIG_CACHE: "${XDG_CACHE_HOME:-$HOME/.cache}/npm" # https://github.com/npm/npm/issues/6675#issuecomment-251049832
  NPM_CONFIG_TMP: "${XDG_RUNTIME_DIR:-/run/user/$UID}/npm" # https://github.com/npm/npm/issues/6675#issuecomment-251049832
  NVM_DIR: "${XDG_CONFIG_HOME:-$HOME/.config}/nvm" # otherwise ~/.nvm
  PYENV_ROOT: "${XDG_DATA_HOME:-$HOME/.local/share}/pyenv" # otherwise ~/.pyenv
  PYTHONSTARTUP: "$HOME/.config/dotfiles/data/python/pythonstartup.py"
  RUSTUP_HOME: "${XDG_DATA_HOME:-$HOME/.local/share}/rustup" # otherwise ~/.rustup
  TEXMFHOME: "$HOME/.config/texmf"
  WORKON_HOME: "${XDG_DATA_HOME:-$HOME/.local/share}/virtualenvs" # otherwise ~/.virtualenvs
  # The following 3 lines should not be necessary, but some programs improperly apply the XDG spec
  XDG_CONFIG_HOME: "$HOME/.config"
  XDG_CACHE_HOME: "$HOME/.cache"
  XDG_DATA_HOME: "$HOME/.local/share"